#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim57077e1ad59e0
#$ -o CURL.BIGNASim57077e1ad59e0.out
#$ -e CURL.BIGNASim57077e1ad59e0.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"ANONUSER57077ddc369b7","idTraj":"NAFlex_1tro","name":"BIGNASim57077e1ad59e0-NAFlex_1tro-1_20_1","description":"Subtrajectory of NAFlex_1tro with 1_20_1 frames selected","mask":"name *","frames":"1:20:1","format":"mdcrd"}' http://ms2/download
