#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim56b0ca30d1ec5
#$ -o CURL.BIGNASim56b0ca30d1ec5.out
#$ -e CURL.BIGNASim56b0ca30d1ec5.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"ANONUSER56b06fd3207d4","idTraj":"NAFlex_1p71","name":"BIGNASim56b0ca30d1ec5-NAFlex_1p71-1_5000_1","description":"Subtrajectory of NAFlex_1p71 with 1_5000_1 frames selected","mask":"name *","frames":"1:5000:1","format":"netcdf"}' http://ms2/download
