#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim5706ad1bf14eb
#$ -o CURL.BIGNASim5706ad1bf14eb.out
#$ -e CURL.BIGNASim5706ad1bf14eb.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"ANONUSER5706acfab0f1c","idTraj":"NAFlex_1tro","name":"BIGNASim5706ad1bf14eb-NAFlex_1tro-1_20_1","description":"Subtrajectory of NAFlex_1tro with 1_20_1 frames selected","mask":"name *","frames":"1:20:1","format":"pdb"}' http://ms2/download
