#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim565e461ea3f42
#$ -o CURL.BIGNASim565e461ea3f42.out
#$ -e CURL.BIGNASim565e461ea3f42.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"BNSUSER565e45c619870","idTraj":"NAFlex_DDD_bsc1","name":"BIGNASim565e461ea3f42-NAFlex_DDD_bsc1-1_20_1","description":"Subtrajectory of NAFlex_DDD_bsc1 with 1_20_1 frames selected","mask":"all","frames":"1:20:1","format":"netcdf"}' http://ms2/download
