#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim55cdbed5ca645
#$ -o CURL.BIGNASim55cdbed5ca645.out
#$ -e CURL.BIGNASim55cdbed5ca645.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"NAFlex55cdbab061c7d","idTraj":"NAFlex_1anr","name":"BIGNASim55cdbed5ca645-NAFlex_1anr-1_20_1","description":"Subtrajectory of NAFlex_1anr with 1_20_1 frames selected","mask":"name *","frames":"1:20:1","format":"mdcrd"}' http://ms2/download
