#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim56b489998d26c
#$ -o CURL.BIGNASim56b489998d26c.out
#$ -e CURL.BIGNASim56b489998d26c.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"BNSUSER56b4898213250","idTraj":"NAFlex_1p71","name":"BIGNASim56b489998d26c-NAFlex_1p71-1_20_1","description":"Subtrajectory of NAFlex_1p71 with 1_20_1 frames selected","mask":"name *","frames":"1:20:1","format":"mdcrd"}' http://ms2/download
