#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim55ce1a0e9a3f5
#$ -o CURL.BIGNASim55ce1a0e9a3f5.out
#$ -e CURL.BIGNASim55ce1a0e9a3f5.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"NAFlex55ce160f93d3a","name":"BIGNASim55ce1a0e9a3f5-AAAA-1_5000_100-4trajs","description":"Metatrajectory of fragment AAAA, with frame selection: 1_5000_100, from 4 trajectories: NAFlex_1d89,NAFlex_1fzx,NAFlex_1rvh,NAFlex_1sk5","id_trajs":[4,{"NAFlex_1d89":[4,16,5,15,6,14]},{"NAFlex_1fzx":[3,17,4,16,5,15]},{"NAFlex_1rvh":[2,18]},{"NAFlex_1sk5":[5,11]}],"frames":"1:5000:100","format":"dcd"}' http://ms2/compose
