#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim55ce3b066e893
#$ -o CURL.BIGNASim55ce3b066e893.out
#$ -e CURL.BIGNASim55ce3b066e893.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"NAFlex55ce160f93d3a","name":"BIGNASim55ce3b066e893-AAAAC-1_5000_100-2trajs","description":"Metatrajectory of fragment AAAAC, with frame selection: 1_5000_100, from 2 trajectories: NAFlex_1fzx,NAFlex_1d89","id_trajs":[4],"frames":"1:5000:100","format":"dcd"}' http://ms2/compose
