#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim55e996503f17e
#$ -o CURL.BIGNASim55e996503f17e.out
#$ -e CURL.BIGNASim55e996503f17e.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"NAFlex55e94ee41ddf3","name":"BIGNASim55e996503f17e-AATT-1_5000_500-2trajs","description":"Metatrajectory of fragment AATT, with frame selection: 1_5000_500, from 2 trajectories: NAFlex_DDD_bsc1,NAFlex_DDD_II_2","id_trajs":[4],"frames":"1:5000:500","format":"dcd"}' http://ms2/compose
