#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim55e99eac5967d
#$ -o CURL.BIGNASim55e99eac5967d.out
#$ -e CURL.BIGNASim55e99eac5967d.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"NAFlex55e94ee41ddf3","name":"BIGNASim55e99eac5967d-GCGA-1_5000_100-10trajs","description":"Metatrajectory of fragment GCGA, with frame selection: 1_5000_100, from 10 trajectories: NAFlex_1d89,NAFlex_1pqt,NAFlex_2mhi,NAFlex_36merSPCE,NAFlex_36merTIP3P,NAFlex_56merSPCE,NAFlex_56merTIP3P,NAFlex_A-Ethanol,NAFlex_A2B_1,NAFlex_A2B_2","id_trajs":[4,{"NAFlex_56merSPCE":[26,82]},{"NAFlex_56merTIP3P":[26,82]}],"frames":"1:5000:100","format":"dcd"}' http://ms2/compose
