#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim570577d9ca2f7
#$ -o CURL.BIGNASim570577d9ca2f7.out
#$ -e CURL.BIGNASim570577d9ca2f7.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"BNSUSER56b26bca99811","idTraj":"NAFlex_1tro","name":"BIGNASim570577d9ca2f7-NAFlex_1tro-1_5000_1","description":"Subtrajectory of NAFlex_1tro with 1_5000_1 frames selected","mask":"name *","frames":"1:5000:1","format":"xtc"}' http://ms2/download
