#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim56f9544977ca3
#$ -o CURL.BIGNASim56f9544977ca3.out
#$ -e CURL.BIGNASim56f9544977ca3.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"BNSUSER56b26bca99811","idTraj":"NAFlex_1tro","name":"BIGNASim56f9544977ca3-NAFlex_1tro-1_5000_100","description":"Subtrajectory of NAFlex_1tro with 1_5000_100 frames selected","mask":"name *","frames":"1:5000:100","format":"xtc"}' http://ms2/download
