#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim56b38970b456a
#$ -o CURL.BIGNASim56b38970b456a.out
#$ -e CURL.BIGNASim56b38970b456a.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"BNSUSER56b26bca99811","idTraj":"NAFlex_1kx5","name":"BIGNASim56b38970b456a-NAFlex_1kx5-1_5000_1","description":"Subtrajectory of NAFlex_1kx5 with 1_5000_1 frames selected","mask":"name *","frames":"1:5000:1","format":"xtc"}' http://ms2/download
