#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim57080bf5daf2a
#$ -o CURL.BIGNASim57080bf5daf2a.out
#$ -e CURL.BIGNASim57080bf5daf2a.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"BNSUSER56b26bca99811","idTraj":"NAFlex_3jxc","name":"BIGNASim57080bf5daf2a-NAFlex_3jxc-1_5000_1","description":"Subtrajectory of NAFlex_3jxc with 1_5000_1 frames selected","mask":"name *","frames":"1:5000:1","format":"xtc"}' http://ms2/download
