#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim56b38509b298d
#$ -o CURL.BIGNASim56b38509b298d.out
#$ -e CURL.BIGNASim56b38509b298d.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"BNSUSER56b26bca99811","idTraj":"NAFlex_DDD_II","name":"BIGNASim56b38509b298d-NAFlex_DDD_II-1_600000_500","description":"Subtrajectory of NAFlex_DDD_II with 1_600000_500 frames selected","mask":"name *","frames":"1:600000:500","format":"xtc"}' http://ms2/download
