#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim56b3baeabdfbf
#$ -o CURL.BIGNASim56b3baeabdfbf.out
#$ -e CURL.BIGNASim56b3baeabdfbf.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"BNSUSER56b26bca99811","idTraj":"NAFlex_v106R3t10","name":"BIGNASim56b3baeabdfbf-NAFlex_v106R3t10-1_20_1","description":"Subtrajectory of NAFlex_v106R3t10 with 1_20_1 frames selected","mask":"name *","frames":"1:20:1","format":"xtc"}' http://ms2/download
