#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim571132ca7130b
#$ -o CURL.BIGNASim571132ca7130b.out
#$ -e CURL.BIGNASim571132ca7130b.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"BNSUSER56b26bca99811","idTraj":"NAFlex_2dgc","name":"BIGNASim571132ca7130b-NAFlex_2dgc-1_5000_1","description":"Subtrajectory of NAFlex_2dgc with 1_5000_1 frames selected","mask":"name *","frames":"1:5000:1","format":"xtc"}' http://ms2/download
