#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim56b26c8113389
#$ -o CURL.BIGNASim56b26c8113389.out
#$ -e CURL.BIGNASim56b26c8113389.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"BNSUSER56b26bca99811","idTraj":"NAFlex_DDD_II","name":"BIGNASim56b26c8113389-NAFlex_DDD_II-1_1200000_500","description":"Subtrajectory of NAFlex_DDD_II with 1_1200000_500 frames selected","mask":"name *","frames":"1:1200000:500","format":"xtc"}' http://ms2/download
