#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim56aa8af79b0b9
#$ -o CURL.BIGNASim56aa8af79b0b9.out
#$ -e CURL.BIGNASim56aa8af79b0b9.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"ANONUSER56aa8ae8125e9","idTraj":"NAFlex_DDD_bsc1","name":"BIGNASim56aa8af79b0b9-NAFlex_DDD_bsc1-1_20_1","description":"Subtrajectory of NAFlex_DDD_bsc1 with 1_20_1 frames selected","mask":"name *","frames":"1:20:1","format":"mdcrd"}' http://ms2/download
