#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim56139b0008144
#$ -o CURL.BIGNASim56139b0008144.out
#$ -e CURL.BIGNASim56139b0008144.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"BNSUSER56139a12eb4c4","idTraj":"NAFlex_1anr","name":"BIGNASim56139b0008144-NAFlex_1anr-1_5_1","description":"Subtrajectory of NAFlex_1anr with 1_5_1 frames selected","mask":"name *","frames":"1:5:1","format":"mdcrd"}' http://ms2/download
