#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim57554eab732a1
#$ -o CURL.BIGNASim57554eab732a1.out
#$ -e CURL.BIGNASim57554eab732a1.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"ANONUSER5755460614aff","idTraj":"NAFlex_muAAAA","name":"BIGNASim57554eab732a1-NAFlex_muAAAA-1_20_1","description":"Subtrajectory of NAFlex_muAAAA with 1_20_1 frames selected","mask":"name *","frames":"1:20:1","format":"mdcrd"}' http://m002/download
