#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim55cd9e3cc3aa1
#$ -o CURL.BIGNASim55cd9e3cc3aa1.out
#$ -e CURL.BIGNASim55cd9e3cc3aa1.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"NAFlex55cd90f502db2","idTraj":"NAFlex_1d11","name":"BIGNASim55cd9e3cc3aa1-NAFlex_1d11-1_20_1","description":"Subtrajectory of NAFlex_1d11 with 1_20_1 frames selected","mask":"name *","frames":"1:20:1","format":"mdcrd"}' http://ms2/download
