#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim55cda01012925
#$ -o CURL.BIGNASim55cda01012925.out
#$ -e CURL.BIGNASim55cda01012925.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"NAFlex55cd90f502db2","idTraj":"NAFlex_v106t10","name":"BIGNASim55cda01012925-NAFlex_v106t10-1_20_1","description":"Subtrajectory of NAFlex_v106t10 with 1_20_1 frames selected","mask":"name *","frames":"1:20:1","format":"mdcrd"}' http://ms2/download
