#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim561578f9288cd
#$ -o CURL.BIGNASim561578f9288cd.out
#$ -e CURL.BIGNASim561578f9288cd.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"ANONUSER56157880abbf3","idTraj":"NAFlex_2oue","name":"BIGNASim561578f9288cd-NAFlex_2oue-1_20_1","description":"Subtrajectory of NAFlex_2oue with 1_20_1 frames selected","mask":"name *","frames":"1:20:1","format":"dcd"}' http://ms2/download
