#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim57553a4f8622b
#$ -o CURL.BIGNASim57553a4f8622b.out
#$ -e CURL.BIGNASim57553a4f8622b.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"ANONUSER57552551c7017","idTraj":"NAFlex_muAAAA","name":"BIGNASim57553a4f8622b-NAFlex_muAAAA-1_20_1","description":"Subtrajectory of NAFlex_muAAAA with 1_20_1 frames selected","mask":"name *","frames":"1:20:1","format":"mdcrd"}' http://m002/download
