#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim560fcea4d4c2d
#$ -o CURL.BIGNASim560fcea4d4c2d.out
#$ -e CURL.BIGNASim560fcea4d4c2d.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"BNSUSER56057bbb85b68","idTraj":"NAFlex_BSC1-OL1","name":"BIGNASim560fcea4d4c2d-NAFlex_BSC1-OL1-1_20_1","description":"Subtrajectory of NAFlex_BSC1-OL1 with 1_20_1 frames selected","mask":"name *","frames":"1:20:1","format":"mdcrd"}' http://ms2/download
