#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim55ce5dd4929c4
#$ -o CURL.BIGNASim55ce5dd4929c4.out
#$ -e CURL.BIGNASim55ce5dd4929c4.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"NAFlex55ce551450492","name":"BIGNASim55ce5dd4929c4-CCCC-1_5000_100-4trajs","description":"Metatrajectory of fragment CCCC, with frame selection: 1_5000_100, from 4 trajectories: NAFlex_1j5n,NAFlex_1vt5,NAFlex_440d,NAFlex_CTAG_8","id_trajs":[4,{"NAFlex_CTAG_8":[10,18]},{"NAFlex_440d":[5,11]}],"frames":"1:5000:100","format":"dcd"}' http://ms2/compose
