#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim55ce61513e599
#$ -o CURL.BIGNASim55ce61513e599.out
#$ -e CURL.BIGNASim55ce61513e599.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"NAFlex55ce551450492","idTraj":"NAFlex_1hlv","name":"BIGNASim55ce61513e599-NAFlex_1hlv-1_20_1","description":"Subtrajectory of NAFlex_1hlv with 1_20_1 frames selected","mask":"name *","frames":"1:20:1","format":"mdcrd"}' http://ms2/download
