#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim55ce6c501c453
#$ -o CURL.BIGNASim55ce6c501c453.out
#$ -e CURL.BIGNASim55ce6c501c453.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"NAFlex55ce551450492","name":"BIGNASim55ce6c501c453-AATA-1_5000_100-3trajs","description":"Metatrajectory of fragment AATA, with frame selection: 1_5000_100, from 3 trajectories: NAFlex_56merA,NAFlex_56merB,NAFlex_56merL","id_trajs":[4,{"NAFlex_56merA":[19,89]},{"NAFlex_56merB":[19,89]},{"NAFlex_56merL":[19,89]}],"frames":"1:5000:100","format":"dcd"}' http://ms2/compose
