#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim560500a212db5
#$ -o CURL.BIGNASim560500a212db5.out
#$ -e CURL.BIGNASim560500a212db5.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"BNSUSER5604fa2365a5f","name":"BIGNASim560500a212db5-CTAG-1_5000_100-3trajs","description":"Metatrajectory of fragment CTAG, with frame selection: 1_5000_100, from 3 trajectories: NAFlex_2l8f,NAFlex_2oue,NAFlex_1iv6","id_trajs":[4],"frames":"1:5000:100","format":"dcd"}' http://ms2/compose
