#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim56af7e88d5106
#$ -o CURL.BIGNASim56af7e88d5106.out
#$ -e CURL.BIGNASim56af7e88d5106.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"ANONUSER56af7c652ab28","idTraj":"NAFlex_1p71","name":"BIGNASim56af7e88d5106-NAFlex_1p71-1_5000_1","description":"Subtrajectory of NAFlex_1p71 with 1_5000_1 frames selected","mask":"name *","frames":"1:5000:1","format":"netcdf"}' http://ms2/download
