#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim56af7fa1545cd
#$ -o CURL.BIGNASim56af7fa1545cd.out
#$ -e CURL.BIGNASim56af7fa1545cd.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"ANONUSER56af7c652ab28","idTraj":"NAFlex_1p71B","name":"BIGNASim56af7fa1545cd-NAFlex_1p71B-1_2000_1","description":"Subtrajectory of NAFlex_1p71B with 1_2000_1 frames selected","mask":"name *","frames":"1:2000:1","format":"mdcrd"}' http://ms2/download
