#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_NAFlex55cd0d8ab9307
#$ -o CURL.NAFlex55cd0d8ab9307.out
#$ -e CURL.NAFlex55cd0d8ab9307.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d [{"idSession":"NAFlex55cd0d8ab9307","name":"NAFlex55cd0d8ab9307-GTAC-1:5000:100-5trajs","desc":"Metatrajectory of fragment GTAC, with frame selection: 1:5000:100, from 5 trajectories: NAFlex_1d11,NAFlex_1dcw,NAFlex_1tro,NAFlex_36merSPCE,NAFlex_36merTIP3P","id_trajs":[4,{"NAFlex_1d11":[1,7]},{"NAFlex_36merSPCE":[16,52]},{"NAFlex_36merTIP3P":[16,52]}],"frames":"1:5000:100","format":"dcd"}] http://ms2/compose
