#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim55e0392e006d0
#$ -o CURL.BIGNASim55e0392e006d0.out
#$ -e CURL.BIGNASim55e0392e006d0.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"NAFlex55df20618ad04","idTraj":"NAFlex_1d89","name":"BIGNASim55e0392e006d0-NAFlex_1d89-1_20_1","description":"Subtrajectory of NAFlex_1d89 with 1_20_1 frames selected","mask":"name *","frames":"1:20:1","format":"mdcrd"}' http://ms2/download
