#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_NAFlex55ca3dffeea09
#$ -o CURL.NAFlex55ca3dffeea09.out
#$ -e CURL.NAFlex55ca3dffeea09.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d [{"idSession":"NAFlex55ca3dffeea09","id_trajs":[4,{"NAFlex_36merTIP3P":[16,52]},{"NAFlex_36merSPCE":[16,52]},{"NAFlex_1d11":[1,7]}],"frames":"1:5000:100","format":"dcd"}] http://ms2/compose
