#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim56fcf1e19c2c8
#$ -o CURL.BIGNASim56fcf1e19c2c8.out
#$ -e CURL.BIGNASim56fcf1e19c2c8.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"ANONUSER56fcf13f5c252","name":"BIGNASim56fcf1e19c2c8-CGAG-1_5000_100-10trajs","description":"Metatrajectory of fragment CGAG, with frame selection: 1_5000_100, from 10 trajectories: NAFlex_GAGA_RNA,NAFlex_AGCG,NAFlex_GGGA,NAFlex_muTCGA,NAFlex_CTAG_1,NAFlex_CTAG_12,NAFlex_CTAG_16,NAFlex_CTAG_19,NAFlex_36merSPCE,NAFlex_36merTIP3P","id_trajs":[4,{"NAFlex_AGCG":[2,30,6,26,10,22]},{"NAFlex_GGGA":[1,31]},{"NAFlex_muTCGA":[13,19]},{"NAFlex_CTAG_1":[11,17]},{"NAFlex_CTAG_12":[10,18]},{"NAFlex_CTAG_16":[10,18]},{"NAFlex_CTAG_19":[10,18]},{"NAFlex_36merSPCE":[13,55]},{"NAFlex_36merTIP3P":[13,55]}],"frames":"1:5000:100","format":"dcd"}' http://ms2/compose
