#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim575960b60386c
#$ -o CURL.BIGNASim575960b60386c.out
#$ -e CURL.BIGNASim575960b60386c.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"ANONUSER57595e40ceb23","idTraj":"NAFlex_muAAAA","name":"BIGNASim575960b60386c-NAFlex_muAAAA-1_20_1","description":"Subtrajectory of NAFlex_muAAAA with 1_20_1 frames selected","mask":"name *","frames":"1:20:1","format":"mdcrd"}' http://ms2.mmb.pcb.ub.es/download
