#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim571182aad7d94
#$ -o CURL.BIGNASim571182aad7d94.out
#$ -e CURL.BIGNASim571182aad7d94.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"ANONUSER57117e2e38d8c","idTraj":"NAFlex_1kx5","name":"BIGNASim571182aad7d94-NAFlex_1kx5-0_1_1","description":"Subtrajectory of NAFlex_1kx5 with 0_1_1 frames selected","mask":"name *","frames":"0:1:1","format":"gro"}' http://ms2/download
