#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_NAFlex55cc9827b0468
#$ -o CURL.NAFlex55cc9827b0468.out
#$ -e CURL.NAFlex55cc9827b0468.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d [{"idSession":"NAFlex55cc9827b0468","idTraj":"NAFlex_1d11","mask":"name *","frames":"1:4:1","format":"dcd"}] http://ms2/download
