#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim55d2e21ecec04
#$ -o CURL.BIGNASim55d2e21ecec04.out
#$ -e CURL.BIGNASim55d2e21ecec04.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"NAFlex55d099baf125c","name":"BIGNASim55d2e21ecec04-CTAG-1_5000_100-3trajs","description":"Metatrajectory of fragment CTAG, with frame selection: 1_5000_100, from 3 trajectories: NAFlex_CTAG_29,NAFlex_CTAG_28,NAFlex_CTAG_27","id_trajs":[4,{"NAFlex_CTAG_29":[6,22]},{"NAFlex_CTAG_28":[6,22]},{"NAFlex_CTAG_27":[6,22]}],"frames":"1:5000:100","format":"dcd"}' http://ms2/compose
