#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_NAFlex55cc6f6576053
#$ -o CURL.NAFlex55cc6f6576053.out
#$ -e CURL.NAFlex55cc6f6576053.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d [{"idSession":"NAFlex55cc6f6576053","id_trajs":[4,{"NAFlex_1d11":[1,7]},{"NAFlex_36merSPCE":[16,52]},{"NAFlex_36merTIP3P":[16,52]}],"frames":"1:5000:100","format":"dcd"}] http://ms2/compose
