#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim57514092f20fe
#$ -o CURL.BIGNASim57514092f20fe.out
#$ -e CURL.BIGNASim57514092f20fe.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"ANONUSER57512f8058af0","idTraj":"NAFlex_MuG_TRF1","name":"BIGNASim57514092f20fe-NAFlex_MuG_TRF1-1_20_1","description":"Subtrajectory of NAFlex_MuG_TRF1 with 1_20_1 frames selected","mask":"name *","frames":"1:20:1","format":"mdcrd"}' http://m002/download
