#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim55ce5a870ebab
#$ -o CURL.BIGNASim55ce5a870ebab.out
#$ -e CURL.BIGNASim55ce5a870ebab.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"NAFlex55ce59747460b","idTraj":"NAFlex_1hlv","name":"BIGNASim55ce5a870ebab-NAFlex_1hlv-1_2000_1","description":"Subtrajectory of NAFlex_1hlv with 1_2000_1 frames selected","mask":"name *","frames":"1:2000:1","format":"dcd"}' http://ms2/download
