#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim55ce606619e01
#$ -o CURL.BIGNASim55ce606619e01.out
#$ -e CURL.BIGNASim55ce606619e01.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"NAFlex55ce59747460b","idTraj":"NAFlex_DDD_GMX_CPU","name":"BIGNASim55ce606619e01-NAFlex_DDD_GMX_CPU-1_2000_1","description":"Subtrajectory of NAFlex_DDD_GMX_CPU with 1_2000_1 frames selected","mask":"name *","frames":"1:2000:1","format":"mdcrd"}' http://ms2/download
