#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim56ec06ca59870
#$ -o CURL.BIGNASim56ec06ca59870.out
#$ -e CURL.BIGNASim56ec06ca59870.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"ANONUSER56ec06996d314","idTraj":"NAFlex_DDD_bsc1","name":"BIGNASim56ec06ca59870-NAFlex_DDD_bsc1-1_5000_1","description":"Subtrajectory of NAFlex_DDD_bsc1 with 1_5000_1 frames selected","mask":"name *","frames":"1:5000:1","format":"netcdf"}' http://ms2/download
