#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim55cda677e3e8f
#$ -o CURL.BIGNASim55cda677e3e8f.out
#$ -e CURL.BIGNASim55cda677e3e8f.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"NAFlex55cd95bfd066c","name":"BIGNASim55cda677e3e8f-ACGT-1_5000_100-1trajs","description":"Metatrajectory of fragment ACGT, with frame selection: 1_5000_100, from 1 trajectories: NAFlex_1kx5","id_trajs":[4],"frames":"1:5000:100","format":"mdcrd"}' http://ms2/compose
