#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim55cd95d512445
#$ -o CURL.BIGNASim55cd95d512445.out
#$ -e CURL.BIGNASim55cd95d512445.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"NAFlex55cd95bfd066c","name":"BIGNASim55cd95d512445-ACTT-1_5000_100-1trajs","description":"Metatrajectory of fragment ACTT, with frame selection: 1_5000_100, from 1 trajectories: NAFlex_1kx5","id_trajs":[4,{"NAFlex_1kx5":[115,175]}],"frames":"1:5000:100","format":"mdcrd"}' http://ms2/compose
