#!/bin/csh
# generated by BIGNASim metatrajectory generator
cd 

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d [{"idSession":"NAFlex55c91c8b336df","id_trajs":[4,{"NAFlex_1p71":[8,26]},{"NAFlex_1p71B":[7,23]},{"NAFlex_1rvh":[4,16]},{"NAFlex_1zgw":[3,29]},{"NAFlex_A-Ethanol":[4,16]},{"NAFlex_A2B_1":[4,16]},{"NAFlex_A2B_2":[4,16]},{"NAFlex_A2B_3":[4,16]},{"NAFlex_A2B_4":[4,16]},{"NAFlex_A2B_5":[4,16]},{"NAFlex_BSC1-BSC0":[4,16]},{"NAFlex_BSC1-C36":[4,40,16,28]},{"NAFlex_BSC1-Garcia":[4,16]},{"NAFlex_BSC1-OL1":[4,16]},{"NAFlex_BSC1-OL1-OL4":[4,16]},{"NAFlex_BSC1-OL4":[4,16]},{"NAFlex_D05M":[4,16]},{"NAFlex_DDD_800ns":[4,16]},{"NAFlex_DDD_Amber_CPU":[4,16]},{"NAFlex_DDD_Amber_GPU":[4,16]},{"NAFlex_DDD_GMX_CPU":[4,16]},{"NAFlex_DDD_GMX_GPU":[4,16]},{"NAFlex_DDD_II":[4,16]},{"NAFlex_DDD_II_1":[4,16]},{"NAFlex_DDD_II_2":[4,16]},{"NAFlex_DDD_bsc1":[4,16]},{"NAFlex_DSpcCheatham":[4,16]},{"NAFlex_DSpcDang":[4,16]},{"NAFlex_DTipCheatham":[4,16]},{"NAFlex_DTipDang015M":[4,16]},{"NAFlex_groovebinder":[4,16]}],"frames":"1:5000:100","format":"dcd"}] http://ms2/compose
