#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim55eda0d1c573d
#$ -o CURL.BIGNASim55eda0d1c573d.out
#$ -e CURL.BIGNASim55eda0d1c573d.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"NAFlex55ed3c8c5a656","idTraj":"NAFlex_v100t9","name":"BIGNASim55eda0d1c573d-NAFlex_v100t9-1_20_1","description":"Subtrajectory of NAFlex_v100t9 with 1_20_1 frames selected","mask":"name *","frames":"1:20:1","format":"mdcrd"}' http://ms2/download
