#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim56afd374a0085
#$ -o CURL.BIGNASim56afd374a0085.out
#$ -e CURL.BIGNASim56afd374a0085.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"ANONUSER56afc0a6edba6","idTraj":"NAFlex_2dgc","name":"BIGNASim56afd374a0085-NAFlex_2dgc-1_500000_100","description":"Subtrajectory of NAFlex_2dgc with 1_500000_100 frames selected","mask":"name *","frames":"1:500000:100","format":"xtc"}' http://ms2/download
