#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim5612a12f31b52
#$ -o CURL.BIGNASim5612a12f31b52.out
#$ -e CURL.BIGNASim5612a12f31b52.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"NAFlex560fcf0944ec0","idTraj":"NAFlex_1anr","name":"BIGNASim5612a12f31b52-NAFlex_1anr-1_20_1","description":"Subtrajectory of NAFlex_1anr with 1_20_1 frames selected","mask":"name *","frames":"1:20:1","format":"dcd"}' http://ms2/download
