#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim56bcb33f5057d
#$ -o CURL.BIGNASim56bcb33f5057d.out
#$ -e CURL.BIGNASim56bcb33f5057d.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"ANONUSER56bcb2f26fcec","idTraj":"NAFlex_v100t9","name":"BIGNASim56bcb33f5057d-NAFlex_v100t9-1_2_1","description":"Subtrajectory of NAFlex_v100t9 with 1_2_1 frames selected","mask":"name *","frames":"1:2:1","format":"pdb"}' http://ms2/download
