#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim55cd8ffe5750a
#$ -o CURL.BIGNASim55cd8ffe5750a.out
#$ -e CURL.BIGNASim55cd8ffe5750a.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"NAFlex55cd8fef1e766","name":"BIGNASim55cd8ffe5750a-ACGT-1_5000_100-4trajs","description":"Metatrajectory of fragment ACGT, with frame selection: 1_5000_100, from 4 trajectories: NAFlex_2dgc,NAFlex_56merSPCE,NAFlex_56merTIP3P,NAFlex_ACGT","id_trajs":[4,{"NAFlex_2dgc":[7,25]},{"NAFlex_56merSPCE":[26,82]},{"NAFlex_56merTIP3P":[26,82]},{"NAFlex_ACGT":[4,16]}],"frames":"1:5000:100","format":"mdcrd"}' http://ms2/compose
