#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim5654845d6106a
#$ -o CURL.BIGNASim5654845d6106a.out
#$ -e CURL.BIGNASim5654845d6106a.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"ANONUSER5654843473b0e","idTraj":"NAFlex_BSC1-BSC0","name":"BIGNASim5654845d6106a-NAFlex_BSC1-BSC0-1_20_1","description":"Subtrajectory of NAFlex_BSC1-BSC0 with 1_20_1 frames selected","mask":"name *","frames":"1:20:1","format":"mdcrd"}' http://ms2/download
