#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim55ce3b5ef39a9
#$ -o CURL.BIGNASim55ce3b5ef39a9.out
#$ -e CURL.BIGNASim55ce3b5ef39a9.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"NAFlex55ce3b455ecf6","idTraj":"NAFlex_1kx5","name":"BIGNASim55ce3b5ef39a9-NAFlex_1kx5-1_20_1","description":"Subtrajectory of NAFlex_1kx5 with 1_20_1 frames selected","mask":"name *","frames":"1:20:1","format":"mdcrd"}' http://ms2/download
