#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim56be2fe29faa6
#$ -o CURL.BIGNASim56be2fe29faa6.out
#$ -e CURL.BIGNASim56be2fe29faa6.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"ANONUSER56be2f328d973","idTraj":"NAFlex_v106Bt10","name":"BIGNASim56be2fe29faa6-NAFlex_v106Bt10-1_2_1","description":"Subtrajectory of NAFlex_v106Bt10 with 1_2_1 frames selected","mask":"name *","frames":"1:2:1","format":"xtc"}' http://ms2/download
