#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim55cddd1d9af7b
#$ -o CURL.BIGNASim55cddd1d9af7b.out
#$ -e CURL.BIGNASim55cddd1d9af7b.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"NAFlex55cddd14826d4","idTraj":"NAFlex_1d11","name":"BIGNASim55cddd1d9af7b-NAFlex_1d11-1_20_1","description":"Subtrajectory of NAFlex_1d11 with 1_20_1 frames selected","mask":"name *","frames":"1:20:1","format":"mdcrd"}' http://ms2/download
