#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim5617a46e35e46
#$ -o CURL.BIGNASim5617a46e35e46.out
#$ -e CURL.BIGNASim5617a46e35e46.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"ANONUSER5617a46485055","idTraj":"NAFlex_BSC1-C36","name":"BIGNASim5617a46e35e46-NAFlex_BSC1-C36-1_20_1","description":"Subtrajectory of NAFlex_BSC1-C36 with 1_20_1 frames selected","mask":"name *","frames":"1:20:1","format":"xtc"}' http://ms2/download
