#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim5613bf597d03d
#$ -o CURL.BIGNASim5613bf597d03d.out
#$ -e CURL.BIGNASim5613bf597d03d.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"ANONUSER5613b733cc04a","idTraj":"NAFlex_2rn1","name":"BIGNASim5613bf597d03d-NAFlex_2rn1-1_20_1","description":"Subtrajectory of NAFlex_2rn1 with 1_20_1 frames selected","mask":"name *","frames":"1:20:1","format":"mdcrd"}' http://ms2/download
