#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim5613bc51daf66
#$ -o CURL.BIGNASim5613bc51daf66.out
#$ -e CURL.BIGNASim5613bc51daf66.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"ANONUSER5613b733cc04a","idTraj":"NAFlex_1anr","name":"BIGNASim5613bc51daf66-NAFlex_1anr-1_20_1","description":"Subtrajectory of NAFlex_1anr with 1_20_1 frames selected","mask":"name *","frames":"1:20:1","format":"mdcrd"}' http://ms2/download
