#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim5613bc86a808e
#$ -o CURL.BIGNASim5613bc86a808e.out
#$ -e CURL.BIGNASim5613bc86a808e.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"ANONUSER5613b733cc04a","idTraj":"NAFlex_2l8f","name":"BIGNASim5613bc86a808e-NAFlex_2l8f-1_20_1","description":"Subtrajectory of NAFlex_2l8f with 1_20_1 frames selected","mask":"name *","frames":"1:20:1","format":"mdcrd"}' http://ms2/download
