#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim56b26b66c0d64
#$ -o CURL.BIGNASim56b26b66c0d64.out
#$ -e CURL.BIGNASim56b26b66c0d64.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"ANONUSER56b26ab7dda17","idTraj":"NAFlex_DTipDang015M","name":"BIGNASim56b26b66c0d64-NAFlex_DTipDang015M-1_1000000_1000","description":"Subtrajectory of NAFlex_DTipDang015M with 1_1000000_1000 frames selected","mask":"name *","frames":"1:1000000:1000","format":"xtc"}' http://ms2/download
