#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim56faab209f2f6
#$ -o CURL.BIGNASim56faab209f2f6.out
#$ -e CURL.BIGNASim56faab209f2f6.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"ANONUSER56faab047c1b7","idTraj":"NAFlex_1tro","name":"BIGNASim56faab209f2f6-NAFlex_1tro-1_20_1","description":"Subtrajectory of NAFlex_1tro with 1_20_1 frames selected","mask":"name *","frames":"1:20:1","format":"xtc"}' http://ms2/download
