#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim55e6ce4703472
#$ -o CURL.BIGNASim55e6ce4703472.out
#$ -e CURL.BIGNASim55e6ce4703472.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"NAFlex55e6bfd8b2d5b","idTraj":"NAFlex_1anr","name":"BIGNASim55e6ce4703472-NAFlex_1anr-1_20_1","description":"Subtrajectory of NAFlex_1anr with 1_20_1 frames selected","mask":"name *","frames":"1:20:1","format":"mdcrd"}' http://ms2/download
