#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim56b0f37fd3022
#$ -o CURL.BIGNASim56b0f37fd3022.out
#$ -e CURL.BIGNASim56b0f37fd3022.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"ANONUSER56b0ef7b752fe","idTraj":"NAFlex_2dgc","name":"BIGNASim56b0f37fd3022-NAFlex_2dgc-1_5000_1","description":"Subtrajectory of NAFlex_2dgc with 1_5000_1 frames selected","mask":"name *","frames":"1:5000:1","format":"xtc"}' http://ms2/download
