#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim5612a19b9cd2a
#$ -o CURL.BIGNASim5612a19b9cd2a.out
#$ -e CURL.BIGNASim5612a19b9cd2a.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"BNSUSER56095dac2149e","idTraj":"NAFlex_1anr","name":"BIGNASim5612a19b9cd2a-NAFlex_1anr-1_20_1","description":"Subtrajectory of NAFlex_1anr with 1_20_1 frames selected","mask":"name *","frames":"1:20:1","format":"xtc"}' http://ms2/download
