#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim5617ba2feb18d
#$ -o CURL.BIGNASim5617ba2feb18d.out
#$ -e CURL.BIGNASim5617ba2feb18d.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"BNSUSER56095dac2149e","idTraj":"NAFlex_2l8f","name":"BIGNASim5617ba2feb18d-NAFlex_2l8f-1_20_1","description":"Subtrajectory of NAFlex_2l8f with 1_20_1 frames selected","mask":"name *","frames":"1:20:1","format":"mdcrd"}' http://ms2/download
