#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim5767cecb9c389
#$ -o CURL.BIGNASim5767cecb9c389.out
#$ -e CURL.BIGNASim5767cecb9c389.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"ANONUSER5767a5d9b2d89","idTraj":"NAFlex_muAAAA","name":"BIGNASim5767cecb9c389-NAFlex_muAAAA-1_20_1","description":"Subtrajectory of NAFlex_muAAAA with 1_20_1 frames selected","mask":"name *","frames":"1:20:1","format":"mdcrd"}' http://ms2.mmb.pcb.ub.es/download
