#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim55e59a81c3275
#$ -o CURL.BIGNASim55e59a81c3275.out
#$ -e CURL.BIGNASim55e59a81c3275.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"NAFlex55e556e74c8b0","name":"BIGNASim55e59a81c3275-ACGC-1_5000_100-10trajs","description":"Metatrajectory of fragment ACGC, with frame selection: 1_5000_100, from 10 trajectories: NAFlex_2l8q,NAFlex_2m2c,NAFlex_2mhi,NAFlex_TCGA,NAFlex_TCGAhmet,NAFlex_TCGAmet,NAFlex_lks1,NAFlex_lks4,NAFlex_rna1,NAFlex_rna4","id_trajs":[4,{"NAFlex_rna4":[10,22]},{"NAFlex_rna1":[8,24]},{"NAFlex_lks4":[10,22]},{"NAFlex_lks1":[8,24]},{"NAFlex_TCGAmet":[7,13]},{"NAFlex_TCGAhmet":[7,13]},{"NAFlex_TCGA":[7,13]},{"NAFlex_2mhi":[4,98]},{"NAFlex_2m2c":[9,15]}],"frames":"1:5000:100","format":"dcd"}' http://ms2/compose
