#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim55e59c36c8bf5
#$ -o CURL.BIGNASim55e59c36c8bf5.out
#$ -e CURL.BIGNASim55e59c36c8bf5.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"NAFlex55e556e74c8b0","name":"BIGNASim55e59c36c8bf5-ACGC-1_5000_100-10trajs","description":"Metatrajectory of fragment ACGC, with frame selection: 1_5000_100, from 10 trajectories: NAFlex_2l8q,NAFlex_2m2c,NAFlex_2mhi,NAFlex_TCGA,NAFlex_TCGAhmet,NAFlex_TCGAmet,NAFlex_lks1,NAFlex_lks4,NAFlex_rna1,NAFlex_rna4","id_trajs":[4],"frames":"1:5000:100","format":"dcd"}' http://ms2/compose
