#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim55ce039d03ff5
#$ -o CURL.BIGNASim55ce039d03ff5.out
#$ -e CURL.BIGNASim55ce039d03ff5.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"NAFlex55cde6229ec5a","name":"BIGNASim55ce039d03ff5-GCAT-1_5000_100-5trajs","description":"Metatrajectory of fragment GCAT, with frame selection: 1_5000_100, from 5 trajectories: NAFlex_1d11,NAFlex_1dcw,NAFlex_1tro,NAFlex_36merSPCE,NAFlex_36merTIP3P","id_trajs":[4],"frames":"1:5000:100","format":"dcd"}' http://ms2/compose
