#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim55cdf59f94818
#$ -o CURL.BIGNASim55cdf59f94818.out
#$ -e CURL.BIGNASim55cdf59f94818.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"NAFlex55cde6229ec5a","name":"BIGNASim55cdf59f94818-ACGT-1_5000_100-5trajs","description":"Metatrajectory of fragment ACGT, with frame selection: 1_5000_100, from 5 trajectories: NAFlex_1d11,NAFlex_1dcw,NAFlex_1tro,NAFlex_36merSPCE,NAFlex_36merTIP3P","id_trajs":[4],"frames":"1:5000:100","format":"dcd"}' http://ms2/compose
