#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim5742e5624ae47
#$ -o CURL.BIGNASim5742e5624ae47.out
#$ -e CURL.BIGNASim5742e5624ae47.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"ANONUSER5742d52170784","idTraj":"NAFlex_DDD_bsc1","name":"BIGNASim5742e5624ae47-NAFlex_DDD_bsc1-1_20_1","description":"Subtrajectory of NAFlex_DDD_bsc1 with 1_20_1 frames selected","mask":"name *","frames":"1:20:1","format":"netcdf"}' http://m002/download
