#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim560907975684d
#$ -o CURL.BIGNASim560907975684d.out
#$ -e CURL.BIGNASim560907975684d.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"BNSUSER5609036ca1bb1","idTraj":"NAFlex_1iv6","name":"BIGNASim560907975684d-NAFlex_1iv6-1_20_1","description":"Subtrajectory of NAFlex_1iv6 with 1_20_1 frames selected","mask":"name *","frames":"1:20:1","format":"mdcrd"}' http://ms2/download
