#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim5619370e7ba05
#$ -o CURL.BIGNASim5619370e7ba05.out
#$ -e CURL.BIGNASim5619370e7ba05.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"ANONUSER561936e33e39e","idTraj":"NAFlex_2l8f","name":"BIGNASim5619370e7ba05-NAFlex_2l8f-1_20_1","description":"Subtrajectory of NAFlex_2l8f with 1_20_1 frames selected","mask":"name *","frames":"1:20:1","format":"mdcrd"}' http://ms2/download
