#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim56b3ad156ff10
#$ -o CURL.BIGNASim56b3ad156ff10.out
#$ -e CURL.BIGNASim56b3ad156ff10.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"ANONUSER56b3acf18e508","idTraj":"NAFlex_2dgc","name":"BIGNASim56b3ad156ff10-NAFlex_2dgc-1_5000_1","description":"Subtrajectory of NAFlex_2dgc with 1_5000_1 frames selected","mask":"name *","frames":"1:5000:1","format":"xtc"}' http://ms2/download
