#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim5617dbf95b028
#$ -o CURL.BIGNASim5617dbf95b028.out
#$ -e CURL.BIGNASim5617dbf95b028.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"ANONUSER5617d0a2ed010","name":"BIGNASim5617dbf95b028-ACGT-1_5000_100-3trajs","description":"Metatrajectory of fragment ACGT, with frame selection: 1_5000_100, from 3 trajectories: NAFlex_56merTIP3P,NAFlex_ACGT,NAFlex_56merSPCE","id_trajs":[4,{"NAFlex_56merTIP3P":[26,82]},{"NAFlex_ACGT":[4,16]},{"NAFlex_56merSPCE":[26,82]}],"frames":"1:5000:100","format":"dcd"}' http://ms2/compose
