#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim56a751c43ee5d
#$ -o CURL.BIGNASim56a751c43ee5d.out
#$ -e CURL.BIGNASim56a751c43ee5d.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"ANONUSER56a745d0964df","idTraj":"NAFlex_1pqt","name":"BIGNASim56a751c43ee5d-NAFlex_1pqt-4999_5000_1","description":"Subtrajectory of NAFlex_1pqt with 4999_5000_1 frames selected","mask":"all","frames":"4999:5000:1","format":"pdb"}' http://ms2/download
