#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim56a7518456821
#$ -o CURL.BIGNASim56a7518456821.out
#$ -e CURL.BIGNASim56a7518456821.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"ANONUSER56a745d0964df","idTraj":"NAFlex_1pqt","name":"BIGNASim56a7518456821-NAFlex_1pqt-0_20_1","description":"Subtrajectory of NAFlex_1pqt with 0_20_1 frames selected","mask":"all","frames":"0:20:1","format":"pdb"}' http://ms2/download
