#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim5617bb99912cd
#$ -o CURL.BIGNASim5617bb99912cd.out
#$ -e CURL.BIGNASim5617bb99912cd.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"ANONUSER5617bb798686c","idTraj":"NAFlex_1anr","name":"BIGNASim5617bb99912cd-NAFlex_1anr-1_20_1","description":"Subtrajectory of NAFlex_1anr with 1_20_1 frames selected","mask":"name *","frames":"1:20:1","format":"mdcrd"}' http://ms2/download
