#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim5617bbd49db2c
#$ -o CURL.BIGNASim5617bbd49db2c.out
#$ -e CURL.BIGNASim5617bbd49db2c.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"ANONUSER5617bb798686c","idTraj":"NAFlex_BSC1-C36","name":"BIGNASim5617bbd49db2c-NAFlex_BSC1-C36-1_20_1","description":"Subtrajectory of NAFlex_BSC1-C36 with 1_20_1 frames selected","mask":"name *","frames":"1:20:1","format":"mdcrd"}' http://ms2/download
