#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim5617c24b1fca7
#$ -o CURL.BIGNASim5617c24b1fca7.out
#$ -e CURL.BIGNASim5617c24b1fca7.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"ANONUSER5617bb798686c","idTraj":"NAFlex_2l8f","name":"BIGNASim5617c24b1fca7-NAFlex_2l8f-1_20_1","description":"Subtrajectory of NAFlex_2l8f with 1_20_1 frames selected","mask":"name *","frames":"1:20:1","format":"mdcrd"}' http://ms2/download
