#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim5617be25e91e2
#$ -o CURL.BIGNASim5617be25e91e2.out
#$ -e CURL.BIGNASim5617be25e91e2.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"ANONUSER5617bb798686c","idTraj":"NAFlex_DDD_bsc1","name":"BIGNASim5617be25e91e2-NAFlex_DDD_bsc1-1_2000_1","description":"Subtrajectory of NAFlex_DDD_bsc1 with 1_2000_1 frames selected","mask":"name *","frames":"1:2000:1","format":"mdcrd"}' http://ms2/download
