#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim56698f8724160
#$ -o CURL.BIGNASim56698f8724160.out
#$ -e CURL.BIGNASim56698f8724160.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"ANONUSER56697b40c2a67","idTraj":"NAFlex_HTQ","name":"BIGNASim56698f8724160-NAFlex_HTQ-1_5000_10","description":"Subtrajectory of NAFlex_HTQ with 1_5000_10 frames selected","mask":"name *","frames":"1:5000:10","format":"xtc"}' http://ms2/download
