#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim566a96e449459
#$ -o CURL.BIGNASim566a96e449459.out
#$ -e CURL.BIGNASim566a96e449459.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"ANONUSER56697b40c2a67","idTraj":"NAFlex_HTQ","name":"BIGNASim566a96e449459-NAFlex_HTQ-20000_25000_50","description":"Subtrajectory of NAFlex_HTQ with 20000_25000_50 frames selected","mask":"name *","frames":"20000:25000:50","format":"xtc"}' http://ms2/download
