#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim5669921f68978
#$ -o CURL.BIGNASim5669921f68978.out
#$ -e CURL.BIGNASim5669921f68978.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"ANONUSER56697b40c2a67","idTraj":"NAFlex_HTQ","name":"BIGNASim5669921f68978-NAFlex_HTQ-5000_6000_1","description":"Subtrajectory of NAFlex_HTQ with 5000_6000_1 frames selected","mask":"name *","frames":"5000:6000:1","format":"xtc"}' http://ms2/download
