#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim566aab593d882
#$ -o CURL.BIGNASim566aab593d882.out
#$ -e CURL.BIGNASim566aab593d882.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"ANONUSER56697b40c2a67","idTraj":"NAFlex_HTQ","name":"BIGNASim566aab593d882-NAFlex_HTQ-1_10000_10","description":"Subtrajectory of NAFlex_HTQ with 1_10000_10 frames selected","mask":"name *","frames":"1:10000:10","format":"xtc"}' http://ms2/download
