#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim566a96b6457e1
#$ -o CURL.BIGNASim566a96b6457e1.out
#$ -e CURL.BIGNASim566a96b6457e1.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"ANONUSER56697b40c2a67","idTraj":"NAFlex_HTQ","name":"BIGNASim566a96b6457e1-NAFlex_HTQ-15000_19999_50","description":"Subtrajectory of NAFlex_HTQ with 15000_19999_50 frames selected","mask":"name *","frames":"15000:19999:50","format":"xtc"}' http://ms2/download
