#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim56698c2046a8c
#$ -o CURL.BIGNASim56698c2046a8c.out
#$ -e CURL.BIGNASim56698c2046a8c.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"ANONUSER56697b40c2a67","idTraj":"NAFlex_HTQ","name":"BIGNASim56698c2046a8c-NAFlex_HTQ-1_100000_20","description":"Subtrajectory of NAFlex_HTQ with 1_100000_20 frames selected","mask":"name *","frames":"1:100000:20","format":"dcd"}' http://ms2/download
