#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim566992614d118
#$ -o CURL.BIGNASim566992614d118.out
#$ -e CURL.BIGNASim566992614d118.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"ANONUSER56697b40c2a67","idTraj":"NAFlex_HTQ","name":"BIGNASim566992614d118-NAFlex_HTQ-10000_14999_10","description":"Subtrajectory of NAFlex_HTQ with 10000_14999_10 frames selected","mask":"name *","frames":"10000:14999:10","format":"xtc"}' http://ms2/download
