<?php

require "../phplib/genlibraries.php";
require "../phplib/tools.inc.php";
redirectOutside();


if($_REQUEST["type"] != 2) {
    // EXTRACT FILE METADATA FROM DMP FILE
    //$mt   = $GLOBALS['filesMetaCol']->findOne(array('_id' => $_REQUEST["id"]));
    //$tool = $GLOBALS['toolsCol']->findOne(array('_id' => $mt["tool"]));
    $mt   = getGSFile_fromId($_REQUEST["id"]);
    $tool = getTool_fromId($mt["tool"]);
}else{
    // EXTRACT JOB METADATA FROM USER JOBS
	$mt = getUserJobPid($_SESSION['User']['_id'],$_REQUEST["id"]);

}

?>


<h3>Item Details</h3>

<?php 

// Description

if($mt["description"] != "") {
?>
<table class="table table-striped table-bordered">
	<tbody><tr>
			<th><b>Description </b></th>
	</tr>
				<tr>
				<td><?php echo nl2br ($mt["description"]); ?></td>
			</tr>
		</tbody>
</table>
<?php
}

// Validated


if(!isset($mt["validated"]) || $mt["validated"]) {
    $mt['validated'] = "TRUE";
}else{
    $mt['validated'] = "FALSE";
}
?>
<table class="table table-striped table-bordered">
	<tbody><tr>
			<th><b>Valid metadata</b></th>
        	</tr>
			<tr>
			<td><?php echo nl2br ($mt["validated"]); ?></td>
	    	</tr>
	</tbody>
</table>
<?php


// Data_type, file_type, taxon_id and assembly (for files)

if($_REQUEST["type"] == 1) {
    // show data_type, file_type
    $dt = $GLOBALS['dataTypesCol']->findOne(array('_id' => $mt["data_type"]));
    // show taxon_id and assembly
    if(!isset($mt["taxon_id"])){
       $taxon = "Not applicable";
    }elseif($mt['taxon_id'] == 0){
        $taxon = $mt['taxon_id'];
    }else{
        $taxon = fromTaxonID2TaxonName($mt['taxon_id'])." (".$mt['taxon_id'].")";
    }
    if(!isset($mt["refGenome"])){$mt['refGenome'] = "Not applicable";}

    ?>
    <table class="table table-striped table-bordered">
        <tbody>
        <tr>
    	    <th style="width:50%;"><b>Data Type</b></th>
    	    <th><b>File Type</b></th>
    	</tr>
    	<tr>
   			<td><?php echo $dt["name"]; ?></td>
   			<td><?php echo $mt["format"]; ?></td>
    	</tr>
    	</tbody>
    </table>
    <table class="table table-striped table-bordered">
        <tbody>
        <tr>
    	    <th style="width:50%;"><b>Taxon</b></th>
    	    <th><b>Assembly</b></th>
    	</tr>
    	<tr>
   			<td><?php echo $taxon; ?></td>
   			<td><?php echo $mt["refGenome"]; ?></td>
    	</tr>
    	</tbody>
    </table>

<?php
}
?>

<?php

// Tool and Input files

if(isset($mt["tool"]) && isset($mt['input_files'])) {
?>
<table class="table table-striped table-bordered">
	<tbody><tr>
			<th><b>Generated by Tool</b></th>
				       </tr>
			<tr>
				<td><?php echo $tool["name"]; ?></td>
                
			</tr>
	</tbody>
</table>

<table class="table table-striped table-bordered">
	<tbody><tr>
			
			<th><b>Input files</b></th>
	       </tr>
			<tr>
				
                <td><?php
											if (count($mt['input_files'])){
												?>
												<ul class="feeds" id="list-files-run-tools">
																			
												<?php
											 foreach ($mt['input_files'] as $inp){
												//echo $inp."<br/>";
												$path = getAttr_fromGSFileId($inp, 'path');
												$p = explode("/", $path);

												?>
												<li class="tool-122 tool-list-item">
												<div class="col1">
													<div class="cont">
														<div class="cont-col1">
															<div class="label label-sm label-info">
																<i class="fa fa-file"></i>
															</div>
														</div>
														<div class="cont-col2">
															<div class="desc">
																<span class="text-info" style="font-weight:bold;"><?php echo $p[1]; ?>  /</span> <?php echo $p[2]; ?> 
															</div>
														</div>
													</div>
												</div>
												</li>
												<?php

											 }
												?>
											</ul>
											<?php
                     }else{
                         echo "";
                    }?>
                </td>
			</tr>
	</tbody>
</table>
<?php
}
?>

<?php
// FIXME   Temporal fix until cloudName is not stored in metadata. Hardcoded here
if($mt["cloudName"] == "")
    $mt['cloudName'] = $GLOBALS['cloud'];

if($mt["cloudName"] != "") {
?>
<table class="table table-striped table-bordered">
	<tbody><tr>
			<th><b>Execution cloud infrastructure</b></th>
	</tr>
			<tr>
				<td><?php echo $mt['cloudName'];?></td>
			</tr>
	</tbody>
</table>
<?php
}
?>


<?php
if ($_SESSION['User']['Type']== 0 || $_SESSION['User']['Type'] == 1){
?>
<table class="table table-striped table-bordered">
	<tbody><tr>
			<th style="background-color: #e7ecf1;"><b>Metadata resource - <a href="http://multiscale-genomics.readthedocs.io/projects/mg-dm-api/rest.html" title="Data Management RESTful API" target="_blank">DMP</a> (TODO)</b></th>
	</tr>
			<tr>
            <td>
                <a target="_blank" href="<?php echo $GLOBALS['URL'].'mug/api/dmp/file_meta?file_id='.$_REQUEST['id'];?>"><?php echo $GLOBALS['URL'].'mug/api/dmp/file_meta?file_id='.$_REQUEST['id'];?></a>
                <br/>
                <pre style="font-size:0.7em;margin:10px 25px;"><?php echo json_encode($mt, JSON_PRETTY_PRINT);?></pre>
            </td>
			</tr>
	</tbody>
</table>
<table class="table table-striped table-bordered">
	<tbody><tr>
			<th style="background-color: #e7ecf1;"><b>Resource location (TODO)</b></th>
	</tr>
			<tr>
			<td><?php echo $mt['path'];?></td>
			</tr>
	</tbody>
</table>
<?php
}
?>


<?php

// SHOWING AUXILIAR FILES ACCORDING DMP FILE
if($_REQUEST["type"] == 0) {

    $path = dirname($mt['logPath']);
    //$p = getGSFile_fromId($_REQUEST["id"])['path'];
	//$path = __DIR__.'/../files/'.$p.'/';

?>

		<?php if( isset($mt['logPath']) && ($_SESSION['User']['Type'] == 0 || $_SESSION['User']['Type'] == 1) ) { ?>
		<table class="table table-striped table-bordered">
			<tbody><tr>
					<th style="background-color: #e7ecf1;"><b>Associated files location</b></th>
			</tr>
					<tr>
								<td><?php echo $path;?></td>
					</tr>
			</tbody>
		</table>
		<?php } ?>


		<div id="meta-log">

				<?php if(file_exists($mt['logPath'])) { ?>
				<a href="workspace/workspace.php?op=openPlainFileFromPath&fnPath=<?php echo urlencode($mt['logPath']); ?>" class="btn green" target="_blank"><i class="fa fa-file-text-o"></i> VIEW LOG FILE </a>
				<?php }else{ ?>
				<a href="javascript:;" class="btn grey tooltips" data-container="body" data-html="true" data-placement="bottom" data-original-title="<p align='left' style='margin:0'>Fie not available</p>"><i class="fa fa-exclamation-triangle"></i> VIEW LOG FILE </a>
				<?php } ?>

				<?php if(($_SESSION['User']['Type'] == 0) || ($_SESSION['User']['Type'] == 1)) { ?>

				<?php if(file_exists($path.'.submit')) { ?>
				<a href="workspace/workspace.php?op=openPlainFileFromPath&fnPath=<?php echo urlencode($p.'/.submit'); ?>" class="btn green" target="_blank"><i class="fa fa-paper-plane"></i> VIEW SUBMIT FILE </a>
				<?php }else{ ?>
				<a href="javascript:;" class="btn grey tooltips" data-container="body" data-html="true" data-placement="bottom" data-original-title="<p align='left' style='margin:0'>Fie not available</p>"><i class="fa fa-exclamation-triangle"></i> VIEW SUBMIT FILE </a>
				<?php } ?>
				<?php if(file_exists($path.'.config.json')) { ?>
				<a href="workspace/workspace.php?op=openPlainFileFromPath&fnPath=<?php echo urlencode($p.'/.config.json'); ?>" class="btn green" target="_blank"><i class="fa fa-cog"></i> VIEW CONFIG FILE </a>
				<?php }else{ ?>
				<a href="javascript:;" class="btn grey tooltips" data-container="body" data-html="true" data-placement="bottom" data-original-title="<p align='left' style='margin:0'>Fie not available</p>"><i class="fa fa-exclamation-triangle"></i> VIEW CONFIG FILE </a>
				<?php } ?>
				<?php if(file_exists($path.'.input_metadata.json')) { ?>
				<a href="workspace/workspace.php?op=openPlainFileFromPath&fnPath=<?php echo urlencode($p.'/.input_metadata.json'); ?>" class="btn green" target="_blank"><i class="fa fa-tags"></i> VIEW META FILE </a>
				<?php }else{ ?>
				<a href="javascript:;" class="btn grey tooltips" data-container="body" data-html="true" data-placement="bottom" data-original-title="<p align='left' style='margin:0'>Fie not available</p>"><i class="fa fa-exclamation-triangle"></i> VIEW META FILE </a>
				<?php } ?>
				<?php if(file_exists($path.'.results.json')) { ?>
				<a href="workspace/workspace.php?op=openPlainFileFromPath&fnPath=<?php echo urlencode($p.'/.results.json'); ?>" class="btn green" target="_blank"><i class="fa fa-line-chart"></i> VIEW RESULTS FILE </a>
				<?php }else{ ?>
				<a href="javascript:;" class="btn grey tooltips" data-container="body" data-html="true" data-placement="bottom" data-original-title="<p align='left' style='margin:0'>Fie not available</p>"><i class="fa fa-exclamation-triangle"></i> VIEW RESULTS FILE </a>
				<?php } ?>

				<?php } ?>

		</div>

<?php
}
?>

<?php 
// SHOWING AUXILIAR FILES ACCORDING USER JOB 

if($_REQUEST["type"] == 2) {
?>

		<div id="meta-log">

				<?php if(file_exists($mt[$_REQUEST['id']]['log_file'])) { ?>
				<a href="workspace/workspace.php?op=openPlainFileFromPath&fnPath=<?php echo urlencode(fromAbsPath_toPath($mt['log_file'])); ?>" class="btn green" target="_blank"><i class="fa fa-file-text-o"></i> VIEW LOG FILE </a>
				<?php }else{ ?>
				<a href="javascript:;" class="btn grey tooltips" data-container="body" data-html="true" data-placement="bottom" data-original-title="<p align='left' style='margin:0'>Fie not available</p>"><i class="fa fa-exclamation-triangle"></i> VIEW LOG FILE </a>
				<?php } ?>


				<?php if(($_SESSION['User']['Type'] == 0) || ($_SESSION['User']['Type'] == 1)) { ?>

				<?php if(file_exists($mt[$_REQUEST['id']]['submission_file'])) { ?>
				<a href="workspace/workspace.php?op=openPlainFileFromPath&fnPath=<?php echo urlencode($mt[$_REQUEST['id']]['submission_file']); ?>" class="btn green" target="_blank"><i class="fa fa-paper-plane"></i> VIEW SUBMIT FILE </a>
				<?php }else{ ?>
				<a href="javascript:;" class="btn grey tooltips" data-container="body" data-html="true" data-placement="bottom" data-original-title="<p align='left' style='margin:0'>Fie not available</p>"><i class="fa fa-exclamation-triangle"></i> VIEW SUBMIT FILE </a>
				<?php } ?>
				<?php if(file_exists($mt[$_REQUEST['id']]['config_file'])) { ?>
				<a href="workspace/workspace.php?op=openPlainFileFromPath&fnPath=<?php echo urlencode($mt[$_REQUEST['id']]['config_file']); ?>" class="btn green" target="_blank"><i class="fa fa-cog"></i> VIEW CONFIG FILE </a>
				<?php }else{ ?>
				<a href="javascript:;" class="btn grey tooltips" data-container="body" data-html="true" data-placement="bottom" data-original-title="<p align='left' style='margin:0'>Fie not available</p>"><i class="fa fa-exclamation-triangle"></i> VIEW CONFIG FILE </a>
				<?php } ?>
				<?php if(file_exists($mt[$_REQUEST['id']]['metadata_file'])) { ?>
				<a href="workspace/workspace.php?op=openPlainFileFromPath&fnPath=<?php echo urlencode($mt[$_REQUEST['id']]['metadata_file']); ?>" class="btn green" target="_blank"><i class="fa fa-tags"></i> VIEW META FILE </a>
				<?php }else{ ?>
				<a href="javascript:;" class="btn grey tooltips" data-container="body" data-html="true" data-placement="bottom" data-original-title="<p align='left' style='margin:0'>Fie not available</p>"><i class="fa fa-exclamation-triangle"></i> VIEW META FILE </a>
				<?php } ?>
				<?php if(file_exists($mt[$_REQUEST['id']]['stageout_file'])) { ?>
				<a href="workspace/workspace.php?op=openPlainFileFromPath&fnPath=<?php echo urlencode($mt[$_REQUEST['id']]['stageout_file']); ?>" class="btn green" target="_blank"><i class="fa fa-line-chart"></i> VIEW RESULTS FILE </a>
				<?php }else{ ?>
				<a href="javascript:;" class="btn grey tooltips" data-container="body" data-html="true" data-placement="bottom" data-original-title="<p align='left' style='margin:0'>Fie not available</p>"><i class="fa fa-exclamation-triangle"></i> VIEW RESULTS FILE </a>
				<?php } ?>

				<?php } ?>

		</div>

<?php
}
?>
