<?php
require "../phplib/genlibraries.php";
require "../phplib/tools.inc.php";
redirectOutside();


if($_REQUEST["type"] != 2) {
    // EXTRACT FILE METADATA FROM DMP FILE
    $mt   = getGSFile_fromId($_REQUEST["id"]);
    $tool = getTool_fromId($mt["tool"],1);
}else{
    // EXTRACT JOB METADATA FROM USER JOBS
	$job = getUserJobPid($_SESSION['User']['_id'],$_REQUEST["id"]);
	$mt = $job[$_REQUEST["id"]];
}

// check Metadata
if (!$mt){
    print "Sorry, no metadata accessible for this resource";
    exit(0);
}

?> <h3>Item Metadata</h3><?php 

// Description

if($mt["description"] != "") {
?>
<table class="table table-striped table-bordered">
	<tbody><tr>
			<th><b>Description 
				<i class="icon-question tooltips" data-container="body" data-html="true" data-placement="right" data-original-title="<p align='left' style='margin:0'>Tooltip sample</p>"></i>
			</b></th>
	</tr>
				<tr>
				<td><?php echo nl2br ($mt["description"]); ?></td>
			</tr>
		</tbody>
</table>
<?php
}

// Validated


if(!isset($mt["validated"]) || $mt["validated"]) {
    $mt['validated'] = "TRUE";
}else{
    $mt['validated'] = "FALSE";
}
if ($mt['validated'] == "FALSE"){
?>
<table class="table table-striped table-bordered">
	<tbody><tr>
			<th><b>Valid metadata</b></th>
        	</tr>
			<tr>
            <td><?php echo nl2br ($mt["validated"]); if($mt["validated"] == "FALSE") { ?> 
            <a style="margin-left:10px;" href="getdata/editFile.php?fn[]=<?php echo $mt["_id"]; ?>" class="btn btn-xs green">Validate Metadata</a>
                <?php } ?>
            </td>
	    	</tr>
	</tbody>
</table>
<?php
}


// Data_type, file_type, taxon_id, assembly, paired, sorted (for files)

if($_REQUEST["type"] == 1) {
    // show data_type, file_type
    $dt = $GLOBALS['dataTypesCol']->findOne(array('_id' => $mt["data_type"]));
    // show taxon_id and assembly
    if(!isset($mt["taxon_id"])){
       $taxon = "N/A";
    }elseif($mt['taxon_id'] == 0){
        $taxon = $mt['taxon_id'];
    }else{
        $taxon = fromTaxonID2TaxonName($mt['taxon_id'])." (".$mt['taxon_id'].")";
    }
    if(!isset($mt["refGenome"])){$mt['refGenome'] = "N/A";}

    ?>
    <table class="table table-striped table-bordered">
        <tbody>
        <tr>
    	    <th style="width:50%;"><b>Data Type</b></th>
    	    <th><b>File Type</b></th>
    	</tr>
    	<tr>
   			<td><?php echo $dt["name"];if(!isset($dt["name"])) echo "N/A"; ?></td>
   			<td><?php echo $mt["format"]; if(!isset($mt["format"])) echo "N/A"; ?></td>
    	</tr>
    	</tbody>
    </table>
    <table class="table table-striped table-bordered">
        <tbody>
        <tr>
    	    <th style="width:50%;"><b>Taxon</b></th>
    	    <th><b>Assembly</b></th>
    	</tr>
    	<tr>
   			<td><?php echo $taxon; ?></td>
   			<td><?php echo $mt["refGenome"]; ?></td>
    	</tr>
    	</tbody>
    </table>

    <?php
    if(isset($mt["paired"]) || isset($mt["sorted"])){
    ?>
    <table class="table table-striped table-bordered">
        <tbody>
        <tr>
    	    <th style="width:50%;"><b>BAM type</b></th>
    	    <th><b>BAM sorted</b></th>
    	</tr>
    	<tr>
   			<td><?php echo $mt["paired"]. " end"; ?></td>
   			<td><?php if($mt["sorted"] == "sorted"){echo "TRUE";}else{echo "FALSE";} ?></td>
    	</tr>
    	</tbody>
    </table>
    <?php
    }
}
?>

<?php

// Expiration date


$expiration ="";
if (isset($mt['expiration'])){
    if (isset($mt['expiration']->sec)){
        $days2expire = intval(( $mt['expiration']->sec - time() ) / (24 * 3600));
        $mt['expiration'] = strftime('%Y/%m/%d %H:%M', $mt['expiration']->sec);
        if ($days2expire < 0 ){
            $expiration = "File/folder has not expiration date";
        }else{
            if ($days2expire < 7)
                $expiration = $mt['expiration'] ." ( in <span style=\"color:#b30000;font-weight:bold;\">".$days2expire."</span> days)";
            else
                $expiration  =$mt['expiration'] ." ( in $days2expire days)";
        }
    }elseif ($mt['expiration'] == -1){
        $expiration = "This file/folder never expires";
    }else{
        $expiration = $mt['expiration'];
    }
}else{
    $expiration = "File/folder has not expiration date";
}
?>

<table class="table table-striped table-bordered">
	<tbody><tr>
			<th><b>File expiration</b></th>
				       </tr>
			<tr>
				<td><?php echo $expiration; ?></td>
                
			</tr>
	</tbody>
</table>


<?php

// Tool and Input files

if(isset($mt["tool"]) && isset($mt['input_files'])) {
?>
<table class="table table-striped table-bordered">
	<tbody><tr>
			<th><b>Generated by Tool</b></th>
				       </tr>
			<tr>
				<td><?php echo $tool["name"]; ?></td>
                
			</tr>
	</tbody>
</table>

<table class="table table-striped table-bordered">
	<tbody><tr>
			
			<th><b>File source/s</b></th>
	       </tr>
			<tr>
				
                <td><?php
											if (count($mt['input_files'])){
												?>
												<ul class="feeds" id="list-files-run-tools">
																			
												<?php
                                              foreach ($mt['input_files'] as $inp){
												$path = getAttr_fromGSFileId($inp, 'path');
												$p = explode("/", $path);

												?>
												<li class="tool-122 tool-list-item">
												<div class="col1">
													<div class="cont">
														<div class="cont-col1">
															<div class="label label-sm label-info">
																<i class="fa fa-file"></i>
															</div>
														</div>
														<div class="cont-col2">
															<div class="desc">
																<span class="text-info" style="font-weight:bold;"><?php echo $p[1]; ?>  /</span> <?php echo $p[2]; ?> 
															</div>
														</div>
													</div>
												</div>
												</li>
												<?php

											 }
												?>
											</ul>
											<?php
                     }else{
                         echo "";
                    }?>
                </td>
			</tr>
	</tbody>
</table>
<?php
}

// Associated Files

if(isset($mt["associated_files"])) {
?>
<table class="table table-striped table-bordered">
	<tbody><tr>
			
			<th><b>Associated Files</b></th>
	       </tr>
			<tr>
				
                <td><?php
											if (count($mt['associated_files'])){
												?>
												<ul class="feeds" id="list-files-run-tools">
																			
												<?php
											 foreach ($mt['associated_files'] as $inp){
                                                 $path = getAttr_fromGSFileId($inp, 'path');
												$p = explode("/", $path);

												?>
												<li class="tool-122 tool-list-item">
												<div class="col1">
													<div class="cont">
														<div class="cont-col1">
															<div class="label label-sm label-info">
																<i class="fa fa-file"></i>
															</div>
														</div>
														<div class="cont-col2">
															<div class="desc">
																<span class="text-info" style="font-weight:bold;"><?php echo $p[1]; ?>  /</span> <?php echo $p[2]; ?> 
															</div>
														</div>
													</div>
												</div>
												</li>
												<?php

											 }
												?>
											</ul>
											<?php
                     }else{
                         echo "";
                    }?>
                </td>
			</tr>
	</tbody>
</table>
<?php
}


// Arguments

if(isset($mt["arguments"])) {
?>
<table class="table table-striped table-bordered">
	<tbody><tr>
			<th><b>Arguments</b></th>
				       </tr>
			<tr>
                <td>
                    <table class="table table-bordered">
                <?php
                foreach ($mt["arguments"] as $k => $v){
                    if (isset($tool['arguments'][$k]['description'])){
                        $k = $tool['arguments'][$k]['description'];
                    }
                    if(gettype($v) == "array") {
											echo "<tr><td>$k</td><td>";
											foreach($v as $val) echo $val."<br>";
											echo "</td></tr>";
										} else {
											echo "<tr><td>$k</td><td>$v</td></tr>";
										}
                }
                ?>
                    </table>
                </td>
                
			</tr>
	</tbody>
</table>
<?php
}


// cloudName
if(!isset($mt['cloudName']) || strlen($mt["cloudName"]) == 0)
    $mt['cloudName'] = $GLOBALS['cloud'];

if($mt["cloudName"] != "") {
?>
<table class="table table-striped table-bordered">
	<tbody><tr>
			<th><b>Execution cloud infrastructure</b></th>
	</tr>
			<tr>
				<td><?php echo $mt['cloudName'];?></td>
			</tr>
	</tbody>
</table>
<?php
}
?>


<?php
if ($_SESSION['User']['Type']== 0 || $_SESSION['User']['Type'] == 1){
?>

<h3>Development data</h3>

<table class="table table-striped table-bordered">
	<tbody><tr>
			<th style="background-color: #e7ecf1;"><b>Metadata resource - <a href="http://multiscale-genomics.readthedocs.io/projects/mg-dm-api/rest.html" title="Data Management RESTful API" target="_blank">DMP</a> (TODO)</b></th>
	</tr>
			<tr>
            <td>
                <a target="_blank" href="<?php echo $GLOBALS['URL'].'mug/api/dmp/file_meta?file_id='.$_REQUEST['id'];?>"><?php echo $GLOBALS['URL'].'mug/api/dmp/file_meta?file_id='.$_REQUEST['id'];?></a>
                <?php if ($_SESSION['User']['Type']== 0){ ?>
                    <br/>
                    <pre style="font-size:0.7em;margin:10px 25px;"><?php echo json_encode($mt, JSON_PRETTY_PRINT);?></pre>
                <?php } ?>
            </td>
			</tr>
	</tbody>
</table>
<table class="table table-striped table-bordered">
	<tbody><tr>
			<th style="background-color: #e7ecf1;"><b>Resource location (TODO)</b></th>
	</tr>
			<tr>
			<td><?php echo $mt['path'];?></td>
			</tr>
	</tbody>
</table>
<?php
}
?>


<?php

// SHOWING AUXILIAR FILES ACCORDING DMP FILE
if($_REQUEST["type"] == 0) {

    $path = dirname($mt['logPath'])."/";
    //$p = getGSFile_fromId($_REQUEST["id"])['path'];
	//$path = __DIR__.'/../files/'.$p.'/';

?>

		<?php if( isset($mt['logPath']) && ($_SESSION['User']['Type'] == 0 || $_SESSION['User']['Type'] == 1) ) { ?>
		<table class="table table-striped table-bordered">
			<tbody><tr>
					<th style="background-color: #e7ecf1;"><b>Associated files location</b></th>
			</tr>
					<tr>
								<td><?php echo $path;?></td>
					</tr>
			</tbody>
		</table>
		<?php } ?>


		<div id="meta-log">

				<?php if(file_exists($mt['logPath'])) { ?>
				<a href="workspace/workspace.php?op=openPlainFileFromPath&fnPath=<?php echo urlencode($mt['logPath']); ?>" class="btn green" target="_blank"><i class="fa fa-file-text-o"></i> VIEW LOG FILE </a>
				<?php }else{ ?>
				<a href="javascript:;" class="btn grey tooltips" data-container="body" data-html="true" data-placement="bottom" data-original-title="<p align='left' style='margin:0'>Fie not available</p>"><i class="fa fa-exclamation-triangle"></i> VIEW LOG FILE   </a>
				<?php } ?>

				<?php if(($_SESSION['User']['Type'] == 0) || ($_SESSION['User']['Type'] == 1)) { ?>

				<?php if(file_exists($path.'.submit')) { ?>
                <a href="workspace/workspace.php?op=openPlainFileFromPath&fnPath=<?php echo urlencode($path.'.submit'); ?>" class="btn green" target="_blank"><i class="fa fa-paper-plane"></i> VIEW SUBMIT FILE </a>

				<?php }else{ ?>
				<a href="javascript:;" class="btn grey tooltips" data-container="body" data-html="true" data-placement="bottom" data-original-title="<p align='left' style='margin:0'>Fie not available</p>"><i class="fa fa-exclamation-triangle"></i> VIEW SUBMIT FILE </a>
				<?php } ?>
				<?php if(file_exists($path.'.config.json')) { ?>
				<a href="workspace/workspace.php?op=openPlainFileFromPath&fnPath=<?php echo urlencode($path.'.config.json'); ?>" class="btn green" target="_blank"><i class="fa fa-cog"></i> VIEW CONFIG FILE </a>
				<?php }else{ ?>
				<a href="javascript:;" class="btn grey tooltips" data-container="body" data-html="true" data-placement="bottom" data-original-title="<p align='left' style='margin:0'>Fie not available</p>"><i class="fa fa-exclamation-triangle"></i> VIEW CONFIG FILE </a>
				<?php } ?>
				<?php if(file_exists($path.'.input_metadata.json')) { ?>
				<a href="workspace/workspace.php?op=openPlainFileFromPath&fnPath=<?php echo urlencode($path.'.input_metadata.json'); ?>" class="btn green" target="_blank"><i class="fa fa-tags"></i> VIEW META FILE </a>
				<?php }else{ ?>
				<a href="javascript:;" class="btn grey tooltips" data-container="body" data-html="true" data-placement="bottom" data-original-title="<p align='left' style='margin:0'>Fie not available</p>"><i class="fa fa-exclamation-triangle"></i> VIEW META FILE </a>
				<?php } ?>
				<?php if(file_exists($path.'.results.json')) { ?>
				<a href="workspace/workspace.php?op=openPlainFileFromPath&fnPath=<?php echo urlencode($path.'.results.json'); ?>" class="btn green" target="_blank"><i class="fa fa-line-chart"></i> VIEW RESULTS FILE </a>
				<?php }else{ ?>
				<a href="javascript:;" class="btn grey tooltips" data-container="body" data-html="true" data-placement="bottom" data-original-title="<p align='left' style='margin:0'>Fie not available</p>"><i class="fa fa-exclamation-triangle"></i> VIEW RESULTS FILE </a>
				<?php } ?>

				<?php } ?>

		</div>

<?php
}
?>

<?php 
// SHOWING AUXILIAR FILES ACCORDING USER JOB 

if($_REQUEST["type"] == 2) {
?>
		<table class="table table-striped table-bordered">
			<tbody><tr>
					<th style="background-color: #e7ecf1;"><b>Job identifier</b></th>
			</tr>
					<tr>
								<td><?php echo $_REQUEST['id'];?></td>
					</tr>
			</tbody>
		</table>

		<div id="meta-log">

				<?php if(file_exists($mt['log_file'])) { ?>
				<a href="workspace/workspace.php?op=openPlainFileFromPath&fnPath=<?php echo urlencode($mt['log_file']); ?>" class="btn green" target="_blank"><i class="fa fa-file-text-o"></i> VIEW LOG FILE </a>
				<?php }else{ ?>
				<a href="javascript:;" class="btn grey tooltips" data-container="body" data-html="true" data-placement="bottom" data-original-title="<p align='left' style='margin:0'>Fie not available</p>"><i class="fa fa-exclamation-triangle"></i> VIEW LOG FILE </a>
				<?php } ?>


				<?php if(($_SESSION['User']['Type'] == 0) || ($_SESSION['User']['Type'] == 1)) { ?>

				<?php if(file_exists($mt['submission_file'])) { ?>
				<a href="workspace/workspace.php?op=openPlainFileFromPath&fnPath=<?php echo urlencode($mt['submission_file']); ?>" class="btn green" target="_blank"><i class="fa fa-paper-plane"></i> VIEW SUBMIT FILE </a>
				<?php }else{ ?>
				<a href="javascript:;" class="btn grey tooltips" data-container="body" data-html="true" data-placement="bottom" data-original-title="<p align='left' style='margin:0'>Fie not available</p>"><i class="fa fa-exclamation-triangle"></i> VIEW SUBMIT FILE </a>
				<?php } ?>
				<?php if(file_exists($mt['config_file'])) { ?>
				<a href="workspace/workspace.php?op=openPlainFileFromPath&fnPath=<?php echo urlencode($mt['config_file']); ?>" class="btn green" target="_blank"><i class="fa fa-cog"></i> VIEW CONFIG FILE </a>
				<?php }else{ ?>
				<a href="javascript:;" class="btn grey tooltips" data-container="body" data-html="true" data-placement="bottom" data-original-title="<p align='left' style='margin:0'>Fie not available</p>"><i class="fa fa-exclamation-triangle"></i> VIEW CONFIG FILE </a>
				<?php } ?>
				<?php if(file_exists($mt['metadata_file'])) { ?>
				<a href="workspace/workspace.php?op=openPlainFileFromPath&fnPath=<?php echo urlencode($mt['metadata_file']); ?>" class="btn green" target="_blank"><i class="fa fa-tags"></i> VIEW META FILE </a>
				<?php }else{ ?>
				<a href="javascript:;" class="btn grey tooltips" data-container="body" data-html="true" data-placement="bottom" data-original-title="<p align='left' style='margin:0'>Fie not available</p>"><i class="fa fa-exclamation-triangle"></i> VIEW META FILE </a>
				<?php } ?>
				<?php if(file_exists($mt['stageout_file'])) { ?>
				<a href="workspace/workspace.php?op=openPlainFileFromPath&fnPath=<?php echo urlencode($mt['stageout_file']); ?>" class="btn green" target="_blank"><i class="fa fa-line-chart"></i> VIEW RESULTS FILE </a>
				<?php }else{ ?>
				<a href="javascript:;" class="btn grey tooltips" data-container="body" data-html="true" data-placement="bottom" data-original-title="<p align='left' style='margin:0'>Fie not available</p>"><i class="fa fa-exclamation-triangle"></i> VIEW RESULTS FILE </a>
				<?php } ?>

				<?php } ?>

		</div>

<?php
}
?>
