#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim56d8209269be5
#$ -o CURL.BIGNASim56d8209269be5.out
#$ -e CURL.BIGNASim56d8209269be5.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"ANONUSER56d81f2e24611","idTraj":"NAFlex_apsGGC","name":"BIGNASim56d8209269be5-NAFlex_apsGGC-1_20_1","description":"Subtrajectory of NAFlex_apsGGC with 1_20_1 frames selected","mask":"name *","frames":"1:20:1","format":"xtc"}' http://ms2/download
