#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim56d8268ebb9bd
#$ -o CURL.BIGNASim56d8268ebb9bd.out
#$ -e CURL.BIGNASim56d8268ebb9bd.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"ANONUSER56d81f2e24611","idTraj":"NAFlex_apsGGC","name":"BIGNASim56d8268ebb9bd-NAFlex_apsGGC-1_5000_10","description":"Subtrajectory of NAFlex_apsGGC with 1_5000_10 frames selected","mask":"name *","frames":"1:5000:10","format":"xtc"}' http://ms2/download
