#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim56d492cf3a078
#$ -o CURL.BIGNASim56d492cf3a078.out
#$ -e CURL.BIGNASim56d492cf3a078.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"ANONUSER56d48ee6b1048","idTraj":"NAFlex_v106Bt10","name":"BIGNASim56d492cf3a078-NAFlex_v106Bt10-1_5000_50","description":"Subtrajectory of NAFlex_v106Bt10 with 1_5000_50 frames selected","mask":"name *","frames":"1:5000:50","format":"xtc"}' http://ms2/download
