#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim573aa572e7716
#$ -o CURL.BIGNASim573aa572e7716.out
#$ -e CURL.BIGNASim573aa572e7716.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"ANONUSER573aa4ef12e4f","idTraj":"NAFlex_1d11","name":"BIGNASim573aa572e7716-NAFlex_1d11-1_20_1","description":"Subtrajectory of NAFlex_1d11 with 1_20_1 frames selected","mask":"name *","frames":"1:20:1","format":"netcdf"}' http://m002/download
