#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim573ac5f6224a2
#$ -o CURL.BIGNASim573ac5f6224a2.out
#$ -e CURL.BIGNASim573ac5f6224a2.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"ANONUSER573aa4ef12e4f","idTraj":"NAFlex_2hdc","name":"BIGNASim573ac5f6224a2-NAFlex_2hdc-1_5000_1","description":"Subtrajectory of NAFlex_2hdc with 1_5000_1 frames selected","mask":"name *","frames":"1:5000:1","format":"netcdf"}' http://m002/download
