#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim573aa66467dce
#$ -o CURL.BIGNASim573aa66467dce.out
#$ -e CURL.BIGNASim573aa66467dce.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"ANONUSER573aa4ef12e4f","idTraj":"NAFlex_Z-DNA-4M","name":"BIGNASim573aa66467dce-NAFlex_Z-DNA-4M-1_5000_1","description":"Subtrajectory of NAFlex_Z-DNA-4M with 1_5000_1 frames selected","mask":"name *","frames":"1:5000:1","format":"netcdf"}' http://m002/download
