#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_
#$ -o CURL..out
#$ -e CURL..err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d [{"idSession":null,"name":"---0trajs","desc":"Metatrajectory of fragment , with frame selection: , from 0 trajectories: ","id_trajs":null,"frames":null,"format":null}] http://ms2/compose
