#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim57691556430cd
#$ -o CURL.BIGNASim57691556430cd.out
#$ -e CURL.BIGNASim57691556430cd.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"ANONUSER576914cebb403","idTraj":"NAFlex_muAAAA","name":"BIGNASim57691556430cd-NAFlex_muAAAA-1_20_1","description":"Subtrajectory of NAFlex_muAAAA with 1_20_1 frames selected","mask":"name *","frames":"1:20:1","format":"mdcrd"}' http://ms2.mmb.pcb.ub.es/download
