#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim55cf86f48f593
#$ -o CURL.BIGNASim55cf86f48f593.out
#$ -e CURL.BIGNASim55cf86f48f593.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"NAFlex55cf86cdf077b","name":"BIGNASim55cf86f48f593-ACGT-1_5000_50-4trajs","description":"Metatrajectory of fragment ACGT, with frame selection: 1_5000_50, from 4 trajectories: NAFlex_2dgc,NAFlex_56merSPCE,NAFlex_56merTIP3P,NAFlex_ACGT","id_trajs":[4,{"NAFlex_2dgc":[7,25]},{"NAFlex_56merSPCE":[26,82]},{"NAFlex_56merTIP3P":[26,82]},{"NAFlex_ACGT":[4,16]}],"frames":"1:5000:50","format":"dcd"}' http://ms2/compose
