#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim56c7239b41b2a
#$ -o CURL.BIGNASim56c7239b41b2a.out
#$ -e CURL.BIGNASim56c7239b41b2a.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"ANONUSER56c72388592fb","idTraj":"NAFlex_56merTIP3P","name":"BIGNASim56c7239b41b2a-NAFlex_56merTIP3P-1_20_1","description":"Subtrajectory of NAFlex_56merTIP3P with 1_20_1 frames selected","mask":"name *","frames":"1:20:1","format":"dcd"}' http://ms2/download
