#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim55ce393bd96ff
#$ -o CURL.BIGNASim55ce393bd96ff.out
#$ -e CURL.BIGNASim55ce393bd96ff.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"NAFlex55ce102c3f610","idTraj":"NAFlex_1iv6","name":"BIGNASim55ce393bd96ff-NAFlex_1iv6-1_20_1","description":"Subtrajectory of NAFlex_1iv6 with 1_20_1 frames selected","mask":"name *","frames":"1:20:1","format":"mdcrd"}' http://ms2/download
