#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim55ce3dcdb6eea
#$ -o CURL.BIGNASim55ce3dcdb6eea.out
#$ -e CURL.BIGNASim55ce3dcdb6eea.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"NAFlex55ce102c3f610","idTraj":"NAFlex_1j5n","name":"BIGNASim55ce3dcdb6eea-NAFlex_1j5n-1_20_1","description":"Subtrajectory of NAFlex_1j5n with 1_20_1 frames selected","mask":"name *","frames":"1:20:1","format":"mdcrd"}' http://ms2/download
