#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim55ce31506556c
#$ -o CURL.BIGNASim55ce31506556c.out
#$ -e CURL.BIGNASim55ce31506556c.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"NAFlex55ce102c3f610","idTraj":"NAFlex_v106R3t10","name":"BIGNASim55ce31506556c-NAFlex_v106R3t10-1_20_1","description":"Subtrajectory of NAFlex_v106R3t10 with 1_20_1 frames selected","mask":"name *","frames":"1:20:1","format":"mdcrd"}' http://ms2/download
