#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim5669793c9b08d
#$ -o CURL.BIGNASim5669793c9b08d.out
#$ -e CURL.BIGNASim5669793c9b08d.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"ANONUSER56697813b72ed","idTraj":"NAFlex_HTQ","name":"BIGNASim5669793c9b08d-NAFlex_HTQ-1_450000_100","description":"Subtrajectory of NAFlex_HTQ with 1_450000_100 frames selected","mask":"resid 1:22","frames":"1:450000:100","format":"pdb"}' http://ms2/download
