#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim56698cac9c37f
#$ -o CURL.BIGNASim56698cac9c37f.out
#$ -e CURL.BIGNASim56698cac9c37f.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"ANONUSER56697813b72ed","idTraj":"NAFlex_HTQ","name":"BIGNASim56698cac9c37f-NAFlex_HTQ-1_50000_100","description":"Subtrajectory of NAFlex_HTQ with 1_50000_100 frames selected","mask":"resid 1:22","frames":"1:50000:100","format":"xtc"}' http://ms2/download
