#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim566983b12d42e
#$ -o CURL.BIGNASim566983b12d42e.out
#$ -e CURL.BIGNASim566983b12d42e.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"ANONUSER56697813b72ed","idTraj":"NAFlex_HTQ","name":"BIGNASim566983b12d42e-NAFlex_HTQ-1_500000_200","description":"Subtrajectory of NAFlex_HTQ with 1_500000_200 frames selected","mask":"resid 1:22","frames":"1:500000:200","format":"xtc"}' http://ms2/download
