#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim5669815867848
#$ -o CURL.BIGNASim5669815867848.out
#$ -e CURL.BIGNASim5669815867848.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"ANONUSER56697813b72ed","idTraj":"NAFlex_HTQ","name":"BIGNASim5669815867848-NAFlex_HTQ-1_100_1","description":"Subtrajectory of NAFlex_HTQ with 1_100_1 frames selected","mask":"resid 1:22","frames":"1:100:1","format":"pdb"}' http://ms2/download
