#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim55eef65e40f83
#$ -o CURL.BIGNASim55eef65e40f83.out
#$ -e CURL.BIGNASim55eef65e40f83.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"NAFlex55eda0d1c37fe","name":"BIGNASim55eef65e40f83-ACGT-1_5000_100-2trajs","description":"Metatrajectory of fragment ACGT, with frame selection: 1_5000_100, from 2 trajectories: NAFlex_2dgc,NAFlex_ACGT","id_trajs":[4,{"NAFlex_2dgc":[7,25]},{"NAFlex_ACGT":[4,16]}],"frames":"1:5000:100","format":"dcd"}' http://ms2/compose
