#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim56695f527b8e1
#$ -o CURL.BIGNASim56695f527b8e1.out
#$ -e CURL.BIGNASim56695f527b8e1.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"ANONUSER566953ac1c5ec","idTraj":"NAFlex_DDD_bsc1","name":"BIGNASim56695f527b8e1-NAFlex_DDD_bsc1-1_20_1","description":"Subtrajectory of NAFlex_DDD_bsc1 with 1_20_1 frames selected","mask":"resid 1:24","frames":"1:20:1","format":"mdcrd"}' http://ms2/download
