#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim566957ade59a2
#$ -o CURL.BIGNASim566957ade59a2.out
#$ -e CURL.BIGNASim566957ade59a2.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"ANONUSER566953ac1c5ec","idTraj":"NAFlex_Z-DNA-4M","name":"BIGNASim566957ade59a2-NAFlex_Z-DNA-4M-1_946999_1000","description":"Subtrajectory of NAFlex_Z-DNA-4M with 1_946999_1000 frames selected","mask":"resid 1:20","frames":"1:946999:1000","format":"gro"}' http://ms2/download
