#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim5669690d6ec45
#$ -o CURL.BIGNASim5669690d6ec45.out
#$ -e CURL.BIGNASim5669690d6ec45.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"ANONUSER566953ac1c5ec","idTraj":"NAFlex_D05M","name":"BIGNASim5669690d6ec45-NAFlex_D05M-1_20_1","description":"Subtrajectory of NAFlex_D05M with 1_20_1 frames selected","mask":"resid 2:11","frames":"1:20:1","format":"xtc"}' http://ms2/download
