#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim566974f370234
#$ -o CURL.BIGNASim566974f370234.out
#$ -e CURL.BIGNASim566974f370234.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"ANONUSER566953ac1c5ec","idTraj":"NAFlex_HTQ","name":"BIGNASim566974f370234-NAFlex_HTQ-1_500000_1000","description":"Subtrajectory of NAFlex_HTQ with 1_500000_1000 frames selected","mask":"resid 1:22","frames":"1:500000:1000","format":"pdb"}' http://ms2/download
