#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim56695ac35e94e
#$ -o CURL.BIGNASim56695ac35e94e.out
#$ -e CURL.BIGNASim56695ac35e94e.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"ANONUSER566953ac1c5ec","idTraj":"NAFlex_Z-DNA-4M","name":"BIGNASim56695ac35e94e-NAFlex_Z-DNA-4M-1_946999_1000","description":"Subtrajectory of NAFlex_Z-DNA-4M with 1_946999_1000 frames selected","mask":"1:20","frames":"1:946999:1000","format":"trr"}' http://ms2/download
