#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim5669705e5323f
#$ -o CURL.BIGNASim5669705e5323f.out
#$ -e CURL.BIGNASim5669705e5323f.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"ANONUSER566953ac1c5ec","idTraj":"NAFlex_D05M","name":"BIGNASim5669705e5323f-NAFlex_D05M-1_20_1","description":"Subtrajectory of NAFlex_D05M with 1_20_1 frames selected","mask":"resid 2:11","frames":"1:20:1","format":"trr"}' http://ms2/download
