#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim566965df22e77
#$ -o CURL.BIGNASim566965df22e77.out
#$ -e CURL.BIGNASim566965df22e77.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"ANONUSER566953ac1c5ec","idTraj":"NAFlex_D05M","name":"BIGNASim566965df22e77-NAFlex_D05M-1_20_1","description":"Subtrajectory of NAFlex_D05M with 1_20_1 frames selected","mask":"resid 2:11","frames":"1:20:1","format":"gro"}' http://ms2/download
