#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim56c2ed94c2b6a
#$ -o CURL.BIGNASim56c2ed94c2b6a.out
#$ -e CURL.BIGNASim56c2ed94c2b6a.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"ANONUSER56c2ed789ea82","idTraj":"NAFlex_DDD_bsc1","name":"BIGNASim56c2ed94c2b6a-NAFlex_DDD_bsc1-1_2_1","description":"Subtrajectory of NAFlex_DDD_bsc1 with 1_2_1 frames selected","mask":"name *","frames":"1:2:1","format":"mdcrd"}' http://ms2/download
