#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_NAFlex55cd8ec1d0e35
#$ -o CURL.NAFlex55cd8ec1d0e35.out
#$ -e CURL.NAFlex55cd8ec1d0e35.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"NAFlex55cd8ec1d0e35","idTraj":"NAFlex_1fzx","name":"BIGNASim55cd8f2d49aa0-NAFlex_1fzx-1_4_1","description":"Subtrajectory of NAFlex_1fzx with 1_4_1 frames selected","mask":"name *","frames":"1:4:1","format":"mdcrd"}' http://ms2/download
