#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim56abc016a94fa
#$ -o CURL.BIGNASim56abc016a94fa.out
#$ -e CURL.BIGNASim56abc016a94fa.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"ANONUSER56aa49aa7436a","idTraj":"NAFlex_1kx5","name":"BIGNASim56abc016a94fa-NAFlex_1kx5-1_50000_10","description":"Subtrajectory of NAFlex_1kx5 with 1_50000_10 frames selected","mask":"name *","frames":"1:50000:10","format":"xtc"}' http://ms2/download
