#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim56afc0a7006c6
#$ -o CURL.BIGNASim56afc0a7006c6.out
#$ -e CURL.BIGNASim56afc0a7006c6.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"ANONUSER56aa49aa7436a","idTraj":"NAFlex_1kx5","name":"BIGNASim56afc0a7006c6-NAFlex_1kx5-1_5000_10","description":"Subtrajectory of NAFlex_1kx5 with 1_5000_10 frames selected","mask":"name *","frames":"1:5000:10","format":"xtc"}' http://ms2/download
