#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim55ed6c13e3953
#$ -o CURL.BIGNASim55ed6c13e3953.out
#$ -e CURL.BIGNASim55ed6c13e3953.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"NAFlex55ed6752e0304","idTraj":"NAFlex_v100t9","name":"BIGNASim55ed6c13e3953-NAFlex_v100t9-1_20_1","description":"Subtrajectory of NAFlex_v100t9 with 1_20_1 frames selected","mask":"name *","frames":"1:20:1","format":"pdb"}' http://ms2/download
