#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim5617c3177ee63
#$ -o CURL.BIGNASim5617c3177ee63.out
#$ -e CURL.BIGNASim5617c3177ee63.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"ANONUSER5617c30c28feb","idTraj":"NAFlex_2lpw","name":"BIGNASim5617c3177ee63-NAFlex_2lpw-1_20_1","description":"Subtrajectory of NAFlex_2lpw with 1_20_1 frames selected","mask":"name *","frames":"1:20:1","format":"mdcrd"}' http://ms2/download
