#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim56aa490ec99ad
#$ -o CURL.BIGNASim56aa490ec99ad.out
#$ -e CURL.BIGNASim56aa490ec99ad.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"ANONUSER56aa48fc9009c","idTraj":"NAFlex_1p71","name":"BIGNASim56aa490ec99ad-NAFlex_1p71-1_20_1","description":"Subtrajectory of NAFlex_1p71 with 1_20_1 frames selected","mask":"name *","frames":"1:20:1","format":"mdcrd"}' http://ms2/download
