#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim56b0ea655d6c6
#$ -o CURL.BIGNASim56b0ea655d6c6.out
#$ -e CURL.BIGNASim56b0ea655d6c6.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"ANONUSER56b0e97fdb0ed","idTraj":"NAFlex_2dgc","name":"BIGNASim56b0ea655d6c6-NAFlex_2dgc-1_2000_1","description":"Subtrajectory of NAFlex_2dgc with 1_2000_1 frames selected","mask":"name *","frames":"1:2000:1","format":"xtc"}' http://ms2/download
