#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim56b0e98b10e0e
#$ -o CURL.BIGNASim56b0e98b10e0e.out
#$ -e CURL.BIGNASim56b0e98b10e0e.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"ANONUSER56b0e97fdb0ed","idTraj":"NAFlex_2dgc","name":"BIGNASim56b0e98b10e0e-NAFlex_2dgc-1_20_1","description":"Subtrajectory of NAFlex_2dgc with 1_20_1 frames selected","mask":"name *","frames":"1:20:1","format":"netcdf"}' http://ms2/download
