#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim56b32b295edc3
#$ -o CURL.BIGNASim56b32b295edc3.out
#$ -e CURL.BIGNASim56b32b295edc3.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"ANONUSER56b32992c0a6c","name":"BIGNASim56b32b295edc3-CATG-1_5000_100-4trajs","description":"Metatrajectory of fragment CATG, with frame selection: 1_5000_100, from 4 trajectories: NAFlex_32mer,NAFlex_2l8q,NAFlex_2m2c,NAFlex_56merL","id_trajs":[4,{"NAFlex_32mer":[19,41]},{"NAFlex_2l8q":[2,18]},{"NAFlex_2m2c":[3,21]},{"NAFlex_56merL":[46,62]}],"frames":"1:5000:100","format":"dcd"}' http://ms2/compose
