#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_NAFlex55ccbcb7750ae
#$ -o CURL.NAFlex55ccbcb7750ae.out
#$ -e CURL.NAFlex55ccbcb7750ae.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d [{"idSession":"NAFlex55ccbcb7750ae","idTraj":"NAFlex_1d89","mask":"name *","frames":"1:20:1","format":"dcd"}] http://ms2/download
