#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim55ce6c06acc1c
#$ -o CURL.BIGNASim55ce6c06acc1c.out
#$ -e CURL.BIGNASim55ce6c06acc1c.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"NAFlex55ce64c37e61e","idTraj":"NAFlex_1g14","name":"BIGNASim55ce6c06acc1c-NAFlex_1g14-1_5000_1","description":"Subtrajectory of NAFlex_1g14 with 1_5000_1 frames selected","mask":"name *","frames":"1:5000:1","format":"dcd"}' http://ms2/download
