#!/bin/csh
# generated by BIGNASim metatrajectory generator
#$ -cwd
#$ -N BIGNaSim_curl_call_BIGNASim55ce64d385710
#$ -o CURL.BIGNASim55ce64d385710.out
#$ -e CURL.BIGNASim55ce64d385710.err

# Launching CURL...

# CURL is calling a REST WS that generates the metatrajectory.
curl -i -H "Content-Type: application/json" -X GET -d '{"idSession":"NAFlex55ce64c37e61e","idTraj":"NAFlex_1g14","name":"BIGNASim55ce64d385710-NAFlex_1g14-1_20_1","description":"Subtrajectory of NAFlex_1g14 with 1_20_1 frames selected","mask":"name *","frames":"1:20:1","format":"mdcrd"}' http://ms2/download
